version: 1.0.{build}

environment:
  matrix:
  - COMPILER: gcc
    PLATFORM: mingw64

install:
  # Set Environment
  - SET PATH_ORIGINAL=%PATH%
  - SET "PATH_MINGW64=c:\msys64\mingw64\bin;c:\msys64\usr\bin"
  - SET PATH=%PATH_MINGW64%;%PATH_ORIGINAL%
  - SET MINGW64_DIR=c:/msys64/mingw64
  - SET WORK_DIR=c:\projects
  - cd %WORK_DIR%
  - SET PATH=%PATH%;%WORK_DIR%/Swift/usr/bin
 
  # Install packages
  - pacman -S --noconfirm mingw-w64-x86_64-cmake
  - pacman -S --noconfirm mingw-w64-x86_64-ninja
  - pacman -S --noconfirm mingw-w64-x86_64-clang       
  - pacman -S --noconfirm mingw-w64-x86_64-icu 
  #- wget -q http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-icu-57.1-2-any.pkg.tar.xz
  #- pacman -U --noconfirm mingw-w64-x86_64-icu-57.1-2-any.pkg.tar.xz         
  - pacman -S --noconfirm mingw-w64-x86_64-libxml2     
  - pacman -S --noconfirm mingw-w64-x86_64-wineditline 
  - pacman -S --noconfirm mingw-w64-x86_64-winpthreads 
  - pacman -S --noconfirm mingw-w64-x86_64-pkg-config
  - pacman -S --noconfirm mingw-w64-x86_64-dlfcn
  #- wget -q http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-dlfcn-1.0.0-2-any.pkg.tar.xz
  #- pacman -U --noconfirm mingw-w64-x86_64-dlfcn-1.0.0-2-any.pkg.tar.xz         
  
  # Patch GCC header
  # __float128 is undefined in clang (https://github.com/Alexpux/MINGW-packages/pull/1833)
  - sed -i "s;defined(_GLIBCXX_USE_FLOAT128)$;defined(_GLIBCXX_USE_FLOAT128) \&\& !defined\(__clang__\);" %MINGW64_DIR%/include/c++/*/type_traits
  - sed -i "s;defined(_GLIBCXX_USE_FLOAT128)$;defined(_GLIBCXX_USE_FLOAT128) \&\& !defined\(__clang__\);" %MINGW64_DIR%/include/c++/*/bits/std_abs.h
 
  # Download Swift compiler
  - MKDIR %WORK_DIR%\Swift
  - CD %WORK_DIR%/Swift
  - wget -q https://ci.appveyor.com/api/projects/tinysun212/swift-compiler-builder/artifacts/swift.zip
  - 7z x swift.zip
  - cp -p usr/bin/swift.exe usr/bin/swiftc.exe
  - cp -p usr/bin/swift.exe usr/bin/swift-autolink-extract.exe
  # Setup swift compiler environment needs %WORK_DIR%/Swift/mingw64
  - MKLINK /d mingw64 c:\msys64\mingw64
  
  # Download Foundation module
  - CD %WORK_DIR%/Swift
  - wget -q https://ci.appveyor.com/api/projects/tinysun212/swift-foundation-builder/artifacts/swift_foundation.zip
  - 7z x swift_foundation.zip
  
  # Download wxWidgets 3.0.3
  - CD %WORK_DIR%
  - MKDIR wxWidgets-3.0.3
  - CD wxWidgets-3.0.3
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.3/wxMSW-3.0.3_gcc510TDM_x64_Dev.7z
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.3/wxWidgets-3.0.3-headers.7z
  - 7z x wxMSW-3.0.3_gcc510TDM_x64_Dev.7z
  - 7z x wxWidgets-3.0.3-headers.7z
 
build_script:
  # Build wxc library
  - CD %WORK_DIR%/wxSwift/wxc
  - MKDIR build
  - CD build
  - cmake -G Ninja -DWXWIDGETS_DIR=%WORK_DIR%/wxWidgets-3.0.3 ../src
  - ninja
  
  # Build wx module
  - CD %WORK_DIR%/wxSwift/wx
  # Generating wx.swiftmodule
  - swiftc -emit-module wx.swift wx_const.swift wxc_wrapper.swift -module-name wx -module-link-name wx -O -parse-as-library
  # Compiling wx.swift
  - swiftc -c -module-name wx -O -parse-as-library -force-single-frontend-invocation -o wx.o wx.swift wx_const.swift wxc_wrapper.swift
  # Compiling wxwidgets_patch.cpp
  - clang++ -c wxwidgets_patch.cpp
  # Building libwx.dll
  - SET WXWIDGETS_LIBDIR=%WORK_DIR%/wxWidgets-3.0.3/lib/gcc510TDM_x64_dll
  - clang++ -shared -o libwx.dll wx.o wxwidgets_patch.o -L%WORK_DIR%/Swift/usr/lib/swift/mingw -lswiftCore 
    -L %WORK_DIR%/wxSwift/wxc/build/cpp -lwxC -Wl,--out-implib,libwx.dll.a  
    -L %WXWIDGETS_LIBDIR% -lwxbase30u -lwxbase30u_net -lwxbase30u_xml -lwxexpat -lwxjpeg -lwxmsw30u_adv 
    -lwxmsw30u_aui -lwxmsw30u_core -lwxmsw30u_gl -lwxmsw30u_html -lwxmsw30u_media -lwxmsw30u_propgrid 
    -lwxmsw30u_ribbon -lwxmsw30u_richtext -lwxmsw30u_stc -lwxmsw30u_webview -lwxmsw30u_xrc -lwxpng -lwxregexu 
    -lwxscintilla -lwxtiff -lwxzlib -lShlwapi -Xlinker --allow-multiple-definition
  
after_build:
  - CD %WORK_DIR%/wxSwift/wx
  - MKDIR usr\bin
  - MKDIR usr\lib\swift\mingw\x86_64
  - cp -p wx.swiftmodule wx.swiftdoc libwx.dll.a usr\lib\swift\mingw\x86_64
  - cp -p libwx.dll usr\lib\swift\mingw
  - cp -p libwx.dll usr\bin
  - 7z a wxswift.zip usr
  - mv wxswift.zip %APPVEYOR_BUILD_FOLDER%

test_script:
  - ECHO skip test
  
artifacts:
  - path: wxswift.zip
    name: WXSWIFT
